research_task:
  description: >
    Conduct a thorough research about {company_name}
    Make sure you find the relevant information from all verified sources.
  expected_output: >
    Most relevant information about {company_name} without making any assumptions and must include below parameters; 
    Company website, Company Founders, Year Founded, Headquarters, Number of Employees, Global Presence, Leadership Team, Company Type, Services, Products, 
    Competitors, Tech Partners, Client Names, top 5 news and press. 
  agent: researcher

reporting_task:
  description: >
    Review the context you got for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main parameters, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
